### PR TITLE
write EPmotion driver files

### PR DESCRIPTION
**Pull request by magnulei**
UPDATED "VERSION 2" 14.12.22 

**auto-place-epmotion.py**
- Sort and place samples automatically at step entry
- Sorting for project name first, submitted id second
- Placement in vertical orientation

**EpMotion_normalization_files.py**
Main script has added new features compared to my first version:
- Enabled process-udfs to control max and min volumes from the lims
- All volume calculations are now done in this script (before it was done separately using groovy/LLTK)
- Sorting of samples in csv according to vertical placement in the output plate (before sorted by by default on the input-output map order, which would in most cases be vertical placement, but opened up for errors happening).
- Added information on sample storage placement (samples placed in "DNA for NGS" box on a new step following extraction)
- Changes to accomidate that tubes now enter the step in multi-well containers (compared single containers before)
- Some rearrangement of the csv-file to make it easier to read in the lab

Read comments in the scripts for details.

Scripts will be tested with real samples in the lab before christmas.

@karinlag, I suggest that we review the epmotion step scripts at one of the lims meetings in January

### CODE REVIEW

**Comment by magnulei** [comment]
FYI, @karinlag, I have been spending a couple of days working on this script and making a program to match on the EPMotion pipetting robot (normalization of samples prior to DNA prep on hamilton). Will modify the script for Biomek sample pooling as well (should be quick).

**Comment by magnulei** [comment]
PS: Not sure why both my commits are included in this pull request. Should be in separate ones. Still a git newbie I guess ;) See my other pull request for descripton on the nextera_flex_sample_file.py edit.

**Comment by magnulei** [comment]
Latest commit for fixing bugs and making variables and descriptions more readable. Added feature to make sure that assigned tube positions on the EPMotion deck always starts at rack 1 position 1. Seems to work as intended, but maybe leave the pull request open until we have stress tested it with different scenarios and also tested it in the lab (on the instrument). 
(PS: did a force-push to change my commit message. Working with git from VS Code and it applied an old message for some reason)

We will also need an auto-place of samples going into this step. Placement of tubes in lims is sorted on sample name by default (not possible to change), but we want it sorted based on submitted lims ID (ie the same order as given in the sample submission list). Marius already has a script for auto-placing samples. I just need to do a minor modification to make it sort on submitted lims id. I will push that change into this branch soon.

**Comment by karinlag** [comment]
You've produced quite a bit of code here :)

I suggest you walk us through it in a session in August, and then we will all be able to contribute/understand how this works :)

**Pull request merged**
